const { Conflict } = require('http-errors')
const { v4: uuidv4 } = require('uuid')

const { sendEmail } = require('../../helpers')
const { User } = require('../../models')

const { PORT } = process.env
console.log("üöÄ ~ file: signup.js ~ line 8 ~ PORT", PORT)

const signup = async (req, res) => {
  const { password, email } = req.body
  const user = await User.findOne({ email })

  if (user) {
    throw new Conflict('Email in use')
  }
  const verifyToken = uuidv4()
  console.log("üöÄ ~ file: signup.js ~ line 14 ~ signup ~ verifyToken", verifyToken)
  const newUser = new User({ email, verifyToken })
  newUser.generateAvatar(email)
  newUser.setPassword(password)
  await newUser.save()

  const mail = {
    to: email,
    subject: '–ü—ñ–¥—Ç–≤–µ—Ä–¥–∂–µ–Ω–Ω—è —Ä–µ—î—Å—Ç—Ä–∞—Ü—ñ—ó –Ω–∞ —Å–∞–π—Ç—ñ',
    html: `
    <a
    target="_blank"
    href="http://localhost:${PORT}/api/users/verify/${verifyToken}"
    >
    –ù–∞–∂–º—ñ—Ç—å –¥–ª—è –ø—ñ–¥—Ç–≤–µ—Ä–¥–∂–µ–Ω–Ω—è —Ä–µ—î—Å—Ç—Ä–∞—Ü—ñ—ó
    </a>
    `
  }

  sendEmail(mail)
  res.status(201).json({
    status: 'succes',
    code: 201,
    data: {
      user: {
        email,
        subscription: newUser.subscription
      }
    }
  })
}

module.exports = signup
